[STR_WELCOME]
base = "Hello {COMPANY}!{}{}You are playing a game with FIRS test GS{}{}Git version of this GS is {NUM}"

[STR_EMPTY]
base = ""

[STR_CABBAGE]
base = "{BLUE}Cabbage"

[STR_CABBAGE_TOWN_HAPPY]
base = "happy"

[STR_CABBAGE_TOWN_UNHAPPY]
base = "unhappy"

[STR_CABBAGE_TOWN]
base = "Town is {STRING}{}{}To find out more about this town (including growth and happiness requirements), open the Story Book, and find the page for {TOWN}"

[STR_GRIND_SUB_HEADING]
base = "{YELLOW}{RAW_STRING}"

[STR_GRIND_TEST]
base = "{BLACK}{RAW_STRING}: {WHITE}{RAW_STRING}"

[STR_GRIND_TEST_INDUSTRY_NAME]
base = "{TINY_FONT}{YELLOW}{DOWN_ARROW} {INDUSTRY} {NORMAL_FONT}"

[STR_GRIND_DELAYED_UPDATE]
base = "{BLACK}Note that this won't refresh currently unless Grind is turned off and on in GS settings"

[STR_TOWN_STORY_PAGE_TEST]
base = "{BLACK}Random word (test): {WHITE}{RAW_STRING}"

[STR_TOWN_STORY_PAGE_GROWTH_RATE]
base = "{BLACK}Current growth rate: {WHITE}{RAW_STRING}"

[STR_TOWN_STORY_PAGE_REQUIRED_CARGOS_GROWTH_TITLE]
base = "{YELLOW}Required cargos for growth"

[STR_TOWN_STORY_PAGE_REQUIRED_CARGOS_HAPPINESS_TITLE]
base = "{YELLOW}Required cargos for happiness"

[STR_TOWN_STORY_PAGE_REQUIRED_CARGO_STATS]
base = "{BLACK}Supplied: {WHITE}{CARGO_LONG}"

[STR_TOWN_STORY_INDUSTRY_REPORT_TITLE]
base = "{BLACK}--- Town industries --- {}"

[STR_TOWN_STORY_INDUSTRY_REPORT_ACCEPTED_TITLE]
base = "{BLACK}Required cargo supplied last month"

[STR_TOWN_STORY_INDUSTRY_REPORT_PRODUCED_TITLE]
base = "{BLACK}Cargo produced last month"

[STR_TOWN_STORY_INDUSTRY_REPORT_INDUSTRY_NAME]
base = "{YELLOW}{INDUSTRY}"

[STR_TOWN_STORY_INDUSTRY_REPORT_CARGO_STATS]
base = "{WHITE}{CARGO_LONG}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_TITLE]
base = "{BLACK}Production (permanent) increase history (last 10 events)"

[STR_TOWN_STORY_INDUSTRY_REPORT_NEVER_INCREASED]
base = "{WHITE}- this industry has never permanently increased production"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_SUBSTR]
base = "{WHITE}{DATE_LONG}{}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_1]
base = "{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_2]
base = "{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_3]
base = "{STRING1}{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_4]
base = "{STRING1}{STRING1}{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_5]
base = "{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_6]
base = "{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_7]
base = "{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_8]
base = "{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_9]
base = "{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_HISTORY_DATE_COUNT_10]
base = "{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}{STRING1}"

[STR_TOWN_STORY_INDUSTRY_REPORT_CURRENT_PROD_LEVEL]
base = "{BLACK}Current production level: {WHITE}{NUM}"

[STR_MANUFACTURERS_STORY_PAGE_TEST]
base = "{BLACK}Random word (test): {WHITE}{RAW_STRING}"

[STR_MANUFACTURERS_STORY_PAGE_NAME]
base = "{BLACK}Name: {WHITE}{RAW_STRING}"

[STR_MANUFACTURERS_STORY_PAGE_CATEGORY]
base = "{BLACK}Type: {WHITE}{RAW_STRING}"

[STR_MANUFACTURERS_STORY_PAGE_HQ_TOWN]
base = "{BLACK}HQ town: {WHITE}{TOWN}"

[STR_MANUFACTURERS_STORY_PAGE_VALID_TOWNS]
base = "{BLACK}Valid towns: {WHITE}{RAW_STRING}"

[STR_MANUFACTURERS_STORY_PAGE_INDUSTRIES_OWNED]
base = "{BLACK}Industries owned: {WHITE}{RAW_STRING}"

[STR_CABBAGE_CLICKABLE_TEST]
base = "{BLACK}This is a GS text. {WHITE}Click me for the town story page. {BLACK}Here is some more text."

[STR_INDUSTRY_OWNER]
base = "Owner: {RAW_STRING}"

[STR_INDUSTRY_TOWN_BLACK_HOLE_EXTRA_TEXT_GROWTH]
base = "{BLACK}Deliveries to this industry will contribute to town growth and/or happiness"

[STR_NEWS_INDUSTRY_INCREASES_PRODUCTION]
base = "{INDUSTRY} increases production!"
