[GLOBAL_PRAGMA]
grflangid = "0x56"
plural = "1"

[STR_GRF_DESC]
base = "{ORANGE}FIRS工业扩展包{}{BLACK}由andythenorth, FooBar, planetmaker, Terkhen and Yexo以及其他贡献者呈献。 {SILVER}查看readme获取更多信息，其中包括怎样使用FIRS. {BLACK}License: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "渔场、钻井平台、疏浚区距离海岸的最大距离。"

[STR_PARAM_DESC_ECONOMIES]
base = "每种经济模式对应不同的货物和工业组合。{}{}休闲玩家可以选择简单模式，{SILVER}'基础'{BLACK}经济模式的货物和工业种类比'FIRS'经济模式的种类要少。{}{}FIRS主页提供了每种经济模式更详细的介绍。"

[STR_PARAM_DESC_NO_OPENINGS]
base = "默认的, 游戏进行时，可以新建工业.{}{}如果{SILVER}阻止新建 {BLACK}选项打开，则在游戏时不能新建工业。"

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "海洋产业距离海岸的最大距离。"

[STR_PARAM_NAME_ECONOMIES]
base = "经济"

[STR_PARAM_NAME_NO_OPENINGS]
base = "游戏进行时禁止新建工业"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "无限制"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "调整“较高生产水平”的货物需求率(%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "为“工合”产率调整货物需求(%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "农场、矿场和相似工业，在得到供给后，产量上升，如果供给充足，则进阶为 {SILVER}增强{BLACK}, 然后可达 {SILVER}工合{BLACK}.{}{}默认值比较合适，但你仍然可以在这里修改默认值.{}{}出口型工业的需求是本值的8倍."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "在较高生产水平上有额外产能"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "在“工合”生产水平产率(%)。"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "当需求满足，在农场、矿场以及相似工业产出(作为百分比{SILVER}正常 {BLACK}产率)."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "基础级-温带经济模式"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "基础级-寒带经济模式"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "基础级-热带经济模式"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "进阶级"

[STR_PARAM_VALUE_ECONOMIES_STEELTOWN]
base = "钢铁城"

[STR_CARGO_NAME_ACID]
base = "酸"

[STR_CARGO_NAME_ALCOHOL]
base = "酒"

[STR_CARGO_NAME_BAUXITE]
base = "铝土"

[STR_CARGO_NAME_BEANS]
base = "大豆"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "建筑材料"

[STR_CARGO_NAME_CASSAVA]
base = "木薯"

[STR_CARGO_NAME_CEMENT]
base = "水泥"

[STR_CARGO_NAME_CHEMICALS]
base = "化工品"

[STR_CARGO_NAME_CHLORINE]
base = "氯气"

[STR_CARGO_NAME_CLAY]
base = "粘土"

[STR_CARGO_NAME_COFFEE]
base = "咖啡"

[STR_CARGO_NAME_COKE]
base = "焦炭"

[STR_CARGO_NAME_COPPER]
base = "铜"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "食用油"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "工程物资"

[STR_CARGO_NAME_EXPLOSIVES]
base = "炸药"

[STR_CARGO_NAME_FIBRES]
base = "植物纤维"

[STR_CARGO_NAME_FISH]
base = "鱼"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "农用物资"

[STR_CARGO_NAME_FERTILISER]
base = "化肥"

[STR_CARGO_NAME_FRUITS]
base = "水果"

[STR_CARGO_NAME_KAOLIN]
base = "高岭土"

[STR_CARGO_NAME_LIMESTONE]
base = "石灰岩"

[STR_CARGO_NAME_TIMBER]
base = "木料"

[STR_CARGO_NAME_METAL]
base = "金属"

[STR_CARGO_NAME_MILK]
base = "牛奶"

[STR_CARGO_NAME_MANGANESE]
base = "锰矿"

[STR_CARGO_NAME_NITRATES]
base = "硝酸盐"

[STR_CARGO_NAME_NUTS]
base = "坚果"

[STR_CARGO_NAME_PACKAGING]
base = "包材"

[STR_CARGO_NAME_PEAT]
base = "泥煤"

[STR_CARGO_NAME_PETROL]
base = "石油燃料"

[STR_CARGO_NAME_PHOSPHATE]
base = "磷酸矿"

[STR_CARGO_NAME_PIG_IRON]
base = "生铁"

[STR_CARGO_NAME_POTASH]
base = "钾碱"

[STR_CARGO_NAME_PYRITE_ORE]
base = "黄铁矿"

[STR_CARGO_NAME_QUICKLIME]
base = "生石灰"

[STR_CARGO_NAME_RECYCLABLES]
base = "回收物资"

[STR_CARGO_NAME_SALT]
base = "盐"

[STR_CARGO_NAME_SAND]
base = "沙子"

[STR_CARGO_NAME_SCRAP_METAL]
base = "废金属"

[STR_CARGO_NAME_SLAG]
base = "矿渣"

[STR_CARGO_NAME_SODA_ASH]
base = "碱粉"

[STR_CARGO_NAME_STEEL]
base = "钢材"

[STR_CARGO_NAME_AGGREGATES]
base = "石料"

[STR_CARGO_NAME_SUGAR_BEET]
base = "甜菜"

[STR_CARGO_NAME_SULPHUR]
base = "硫磺"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "车身"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "车辆零件"

[STR_CARGO_NAME_VEHICLES]
base = "车辆"

[STR_CARGO_NAME_WOOL]
base = "羊毛"

[STR_CARGO_NAME_ZINC]
base = "锌"

[STR_CARGO_UNIT_ACID]
base = "{VOLUME} 升酸"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} 酒"

[STR_CARGO_UNIT_BAUXITE]
base = "{WEIGHT} 铝土"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} 吨大豆"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} 建筑材料"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} 吨木薯"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} 吨水泥"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} 化工品"

[STR_CARGO_UNIT_CHLORINE]
base = "{VOLUME} 升氯气"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} 粘土"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} 袋咖啡"

[STR_CARGO_UNIT_COKE]
base = "{WEIGHT} 吨 焦炭"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} 吨铜"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} 升食用油"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} 箱 工程物资"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} 箱 炸药"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} 袋 化肥"

[STR_CARGO_UNIT_FIBRES]
base = "{SIGNED_WORD} 包 植物纤维"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} 鱼"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} 箱 农用物资"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} 水果"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} 吨高岭土"

[STR_CARGO_UNIT_LIMESTONE]
base = "{WEIGHT} 吨石灰岩"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} 木料"

[STR_CARGO_UNIT_LYE]
base = "{VOLUME} 升碱液"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} 吨锰矿"

[STR_CARGO_UNIT_METAL]
base = "{WEIGHT} 金属"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} 牛奶"

[STR_CARGO_UNIT_NICKEL]
base = "{WEIGHT} 吨镍"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} 吨硝酸盐"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} 麻袋坚果"

[STR_CARGO_UNIT_PACKAGING]
base = "{WEIGHT} 吨包材"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT} 吨泥煤"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} 升石油燃料"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} 吨磷酸盐"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} 吨 生铁"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} 吨 钾碱"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} 吨黄铁矿"

[STR_CARGO_UNIT_QUICKLIME]
base = "{WEIGHT} 吨生石灰"

[STR_CARGO_UNIT_RECYCLABLES]
base = "{WEIGHT} 回收物资"

[STR_CARGO_UNIT_SALT]
base = "{WEIGHT} 吨盐"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} 沙子"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} 废金属"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} 吨 矿渣"

[STR_CARGO_UNIT_SODA_ASH]
base = "{WEIGHT} 吨碱粉"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} 吨 钢材"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} 石料"

[STR_CARGO_UNIT_SUGAR_BEET]
base = "{WEIGHT} 甜菜"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} 吨硫磺"

[STR_CARGO_UNIT_VEHICLE_BODIES]
base = "{WEIGHT} 辆车身"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{WEIGHT} 箱车辆零件"

[STR_CARGO_UNIT_VEHICLES]
base = "{WEIGHT} 辆车"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} 包 羊毛"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} 吨锌"

[STR_CID_ACID]
base = "{TINYFONT}酸"

[STR_CID_ALCOHOL]
base = "{TINYFONT}酒"

[STR_CID_BAUXITE]
base = "{TINYFONT}铝"

[STR_CID_BEANS]
base = "{TINYFONT}豆"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}建"

[STR_CID_CASSAVA]
base = "{TINYFONT}薯"

[STR_CID_CEMENT]
base = "{TINYFONT}泥"

[STR_CID_CHEMICALS]
base = "{TINYFONT}化"

[STR_CID_CHLORINE]
base = "{TINYFONT}氯"

[STR_CID_CLAY]
base = "{TINYFONT}粘"

[STR_CID_COFFEE]
base = "{TINYFONT}啡"

[STR_CID_COKE]
base = "{TINYFONT}焦"

[STR_CID_COPPER]
base = "{TINYFONT}铜"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}脂"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}程"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}炸"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}农"

[STR_CID_FERTILISER]
base = "{TINYFONT}肥"

[STR_CID_FIBRES]
base = "{TINYFONT}纤"

[STR_CID_FISH]
base = "{TINYFONT}鱼"

[STR_CID_KAOLIN]
base = "{TINYFONT}岭"

[STR_CID_LIMESTONE]
base = "{TINYFONT}灰"

[STR_CID_TIMBER]
base = "{TINYFONT}料"

[STR_CID_LYE]
base = "{TINYFONT}碱"

[STR_CID_MANGANESE]
base = "{TINYFONT}锰"

[STR_CID_METAL]
base = "{TINYFONT}金"

[STR_CID_MILK]
base = "{TINYFONT}奶"

[STR_CID_NICKEL]
base = "{TINYFONT}镍"

[STR_CID_NITRATES]
base = "{TINYFONT}硝"

[STR_CID_NUTS]
base = "{TINYFONT}坚"

[STR_CID_PACKAGING]
base = "{TINYFONT}包"

[STR_CID_PEAT]
base = "{TINYFONT}泥"

[STR_CID_PETROL]
base = "{TINYFONT}汽"

[STR_CID_PIG_IRON]
base = "{TINYFONT}生"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}磷"

[STR_CID_POTASH]
base = "{TINYFONT}钾"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}黄"

[STR_CID_QUICKLIME]
base = "{TINYFONT}生"

[STR_CID_RECYCLABLES]
base = "{TINYFONT}回"

[STR_CID_SALT]
base = "{TINYFONT}盐"

[STR_CID_SAND]
base = "{TINYFONT}沙"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}废"

[STR_CID_SLAG]
base = "{TINYFONT}渣"

[STR_CID_SODA_ASH]
base = "{TINYFONT}碱"

[STR_CID_STEEL]
base = "{TINYFONT}钢"

[STR_CID_AGGREGATES]
base = "{TINYFONT}石"

[STR_CID_SUGAR_BEET]
base = "{TINYFONT}甜"

[STR_CID_SULPHUR]
base = "{TINYFONT}磺"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}车"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}零"

[STR_CID_VEHICLES]
base = "{TINYFONT}车"

[STR_CID_WOOL]
base = "{TINYFONT}毛"

[STR_CID_ZINC]
base = "{TINYFONT}锌"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS不兼容于Toyland climate"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "须置于雪线以下"

[STR_ERR_LOCATION_NOT_BELOW_SNOWLINE]
base = "必须置于雪线以上"

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "须置于干燥土地"

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "不得置于沙漠"

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "不能置于陡坡"

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "每城镇只允许一个该类工业"

[STR_IND_ALUMINIUM_PLANT]
base = "电解铝厂"

[STR_IND_AMMONIA_PLANT]
base = "制氨厂"

[STR_IND_ARABLE_FARM]
base = "种植园"

[STR_IND_ASSEMBLY_PLANT]
base = "车辆厂"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "吹氧转炉"

[STR_IND_BIOREFINERY]
base = "生物炼制厂"

[STR_IND_BLAST_FURNACE]
base = "高炉"

[STR_IND_BREWERY]
base = "酿酒厂"

[STR_IND_CIDER_MILL]
base = "苹果酒厂"

[STR_IND_BRICK_WORKS]
base = "砖厂"

[STR_IND_BUILDERS_YARD]
base = "建筑工地"

[STR_IND_BULK_TERMINAL]
base = "散装码头"

[STR_IND_CEMENT_PLANT]
base = "水泥厂"

[STR_IND_CHEMICAL_PLANT]
base = "化工厂"

[STR_IND_CLAY_PIT]
base = "粘土矿坑"

[STR_IND_COFFEE_ESTATE]
base = "咖啡屋"

[STR_IND_COKE_OVEN]
base = "炼焦炉"

[STR_IND_COPPER_SMELTER]
base = "炼铜厂"

[STR_IND_DAIRY]
base = "乳品厂"

[STR_IND_DAIRY_FARM]
base = "乳牛场"

[STR_IND_DREDGING_SITE]
base = "疏浚区"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "电弧炉"

[STR_IND_FISHING_GROUND]
base = "渔场"

[STR_IND_FISHING_HARBOUR]
base = "渔港"

[STR_IND_FISHING_VILLAGE]
base = "渔村"

[STR_IND_FLOUR_MILL]
base = "磨坊"

[STR_IND_FOOD_MARKET]
base = "杂货店"

[STR_IND_FOOD_PROCESSOR]
base = "食品加工厂"

[STR_IND_FURNITURE_FACTORY]
base = "家具厂"

[STR_IND_GENERAL_STORE]
base = "综合商店"

[STR_IND_GLASS_WORKS]
base = "玻璃制品厂"

[STR_IND_HARDWARE_STORE]
base = "五金工具店"

[STR_IND_HOTEL]
base = "旅店"

[STR_IND_HERDING_COOP]
base = "狩猎营"

[STR_IND_IRON_WORKS]
base = "炼铁厂"

[STR_IND_SCRAP_YARD]
base = "废料场"

[STR_IND_LIME_KILN]
base = "石灰窑"

[STR_IND_LIMESTONE_MINE]
base = "石灰岩"

[STR_IND_LIQUIDS_TERMINAL]
base = "油品码头"

[STR_IND_TIMBER_YARD]
base = "木材加工厂"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "机械厂"

[STR_IND_MANGANESE_MINE]
base = "锰矿"

[STR_IND_MIXEDFARM]
base = "综合农场"

[STR_IND_NITRATE_MINE]
base = "硝酸盐矿山"

[STR_IND_ORCHARD_PIGGERY]
base = "生态农场"

[STR_IND_PEATLANDS]
base = "泥煤地"

[STR_IND_PETROLPUMP]
base = "加油站"

[STR_IND_PHOSPHATE_MINE]
base = "磷矿山"

[STR_IND_PLASTICS_PLANT]
base = "塑料厂"

[STR_IND_PORT]
base = "港口"

[STR_IND_POTASH_MINE]
base = "钾矿"

[STR_IND_PYRITE_MINE]
base = "黄铁矿山"

[STR_IND_PYRITE_SMELTER]
base = "黄铁矿冶炼厂"

[STR_IND_POWER_PLANT]
base = "发电厂"

[STR_IND_QUARRY]
base = "采石场"

[STR_IND_RANCH]
base = "大牧场"

[STR_IND_RECYCLING_DEPOT]
base = "回收站"

[STR_IND_RECYCLING_PLANT]
base = "回收厂"

[STR_IND_REINDEER_FARM]
base = "驯鹿农场"

[STR_IND_SHEEPFARM]
base = "牧羊场"

[STR_IND_SLAG_GRINDING_PLANT]
base = "磨渣场"

[STR_IND_SMITHY_FORGE]
base = "铁匠铺"

[STR_IND_SODA_ASH_MINE]
base = "碱矿"

[STR_IND_STOCKYARD]
base = "肉联厂"

[STR_IND_SUGAR_REFINERY]
base = "制糖厂"

[STR_IND_SUPPLY_YARD]
base = "供货场"

[STR_IND_TEXTILE_MILL]
base = "纺织厂"

[STR_IND_TRADING_POST]
base = "贸易站"

[STR_IND_TYRE_PLANT]
base = "轮胎工厂"

[STR_IND_VINEYARD]
base = "葡萄园"

[STR_IND_WHARF]
base = "码头"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(已供应)"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "如果{WHITE}任意 {BLACK}所需的货物供应，则{BLACK}产率达到最大"

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}当前产率: {YELLOW}标准{}{}{BLACK}为达到{WHITE}增强{BLACK}需三个月内交付 {SIGNED_WORD}箱物资。{}为达到{WHITE}工合 {BLACK}需交付 {SIGNED_WORD} 箱"

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}当前产率: {YELLOW}增强{}{}{BLACK}为保持此水准，需三个月内交付 {SIGNED_WORD}{}为保持{WHITE}工合 {BLACK}需交付 {SIGNED_WORD}箱"

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}当前产率: {YELLOW}工合{}{} {BLACK}为保持此产率, 需三个月内交付 {SKIP}{SIGNED_WORD} 箱物资"

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}当前产率: {YELLOW}标准{}{}{BLACK}为达到{WHITE}增强{BLACK}需三个月内交付 {SIGNED_WORD} 单位货物{}为达到{WHITE}工合 {BLACK}需交付 {SIGNED_WORD} 单位"

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}当前产率: {YELLOW}增强{}{}{BLACK}为保持次水准，需三个月内交付{SIGNED_WORD} 单位货物。{}为达到{WHITE}工合 {BLACK}需交付 {SIGNED_WORD} 单位"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}当前产率: {YELLOW}工合{}{}{BLACK}为保持此产率，需三个月内交付{SKIP}{SIGNED_WORD} 单位货物"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}位置: {YELLOW}不得修建于雪地或者沙漠。"

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}位置: {YELLOW}不得修建于雪地或者沙漠。"

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}位置: {YELLOW}不能修建于雪地或者沙漠。"

[STR_FUND_FOREST]
base = "{}{BLACK}位置: {YELLOW}不得在沙漠修建。"

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}位置: {YELLOW}不得在雪地修建。"

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}位置: {YELLOW}只能修建于雪地"

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}位置: {YELLOW}不得修建于雪地或者沙漠。"

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}位置: {YELLOW}不得修建于雪地或者沙漠。"

[STR_FUND_VINEYARD]
base = "{}{BLACK}位置: {YELLOW}不得修建于雪地或者沙漠。."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}起始于: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}终结于: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "马市"

[STR_STATION_AUTOMOTIVE]
base = "汽车厂"

[STR_STATION_BAR_GRILL_AND_ROOMS]
base = "度假町"

[STR_STATION_BARNS]
base = "廒圈"

[STR_STATION_BARREL_AND_KEG]
base = "大酒桶"

[STR_STATION_BASE]
base = "基地"

[STR_STATION_BONEYARD]
base = "废料场"

[STR_STATION_BANK_TOP]
base = "大银行"

[STR_STATION_CASTINGS]
base = "铸铁炉"

[STR_STATION_COLLIERY]
base = "煤矿"

[STR_STATION_COPPER_LODE]
base = "铜矿"

[STR_STATION_CREOSOTING]
base = "木馏油"

[STR_STATION_DAIRY_LANE]
base = "牛奶巷"

[STR_STATION_ESTATE]
base = "地产"

[STR_STATION_EXCHANGE]
base = "交易港"

[STR_STATION_FARM_1]
base = "庄园"

[STR_STATION_FARM_2]
base = "草甸"

[STR_STATION_FARM_3]
base = "大农场"

[STR_STATION_FISHMARKET]
base = "鱼市场"

[STR_STATION_FOOD_CORPORATION]
base = "食品厂"

[STR_STATION_FOREST]
base = "原木码头"

[STR_STATION_FORGE]
base = "锻造厂"

[STR_STATION_FURNACE]
base = "火炉"

[STR_STATION_HEAVY_EQUIPMENT_YARD]
base = "重工"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "工厂"

[STR_STATION_HERDING_COOP]
base = "营地"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "工业园区"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "货港"

[STR_STATION_INDUSTRY_HARBOUR_2]
base = "湾浦"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "栈桥"

[STR_STATION_IRONSTONE]
base = "铁石"

[STR_STATION_JOINERS_SHOP]
base = "木匠店"

[STR_STATION_KILNS]
base = "窑"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = "金伯利矿"

[STR_STATION_LIMESTONE_MINES]
base = "石灰岩矿"

[STR_STATION_MANGANESE_MINES]
base = "锰矿"

[STR_STATION_MARKET]
base = "市场"

[STR_STATION_MERCHANTS_LANE]
base = "建材胡同"

[STR_STATION_MILL]
base = "坊"

[STR_STATION_MINE]
base = "矿山路"

[STR_STATION_MOULDINGS]
base = "模具厂"

[STR_STATION_OIL_RIG]
base = "钻井台"

[STR_STATION_ORCHARDS]
base = "圃"

[STR_STATION_PIT]
base = "矿坑"

[STR_STATION_PLANTATION]
base = "种植园"

[STR_STATION_POWERHUNGRY]
base = "电站"

[STR_STATION_PUMPS]
base = "泵站"

[STR_STATION_PYRITES]
base = "黄铁矿床"

[STR_STATION_REFINERY]
base = "炼油厂"

[STR_STATION_RUBBER_COMPANY]
base = "橡胶公司"

[STR_STATION_SALTPETER_WORKS]
base = "硝厂"

[STR_STATION_SHARP_STREET]
base = "角街"

[STR_STATION_SHEEP_FOLD]
base = "羊圈"

[STR_STATION_SHOALS]
base = "滩"

[STR_STATION_SILO]
base = "筒仓"

[STR_STATION_SMELTER]
base = "熔炉"

[STR_STATION_STACKS]
base = "堆"

[STR_STATION_STAMP_AND_PLATE]
base = "雕印坊"

[STR_STATION_SUGAR_COMPANY]
base = "糖厂"

[STR_STATION_TANK_FARM]
base = "油库"

[STR_STATION_TAPPERS_SHED]
base = "工棚"

[STR_STATION_TOWN_1]
base = "市中心"

[STR_STATION_TOWN_2]
base = "大街"

[STR_STATION_TOWN_3]
base = "杂货店"

[STR_STATION_TRONA_BEDS]
base = "碱床"

[STR_STATION_WATER]
base = "沙堤"

[STR_STATION_WEAVE_AND_DYE]
base = "纺染所"

[STR_STATION_WELLS]
base = "油井"

[STR_STATION_WINERY]
base = "酒厂"
